# Generated by Django 4.2.23 on 2025-08-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_number', models.CharField(blank=True, db_index=True, max_length=5, null=True)),
                ('machine_name', models.CharField(blank=True, db_index=True, max_length=5, null=True)),
                ('x_limits', models.CharField(blank=True, db_index=True, max_length=5, null=True)),
                ('y_limits', models.CharField(blank=True, db_index=True, max_length=5, null=True)),
                ('z_limits', models.CharField(blank=True, db_index=True, max_length=5, null=True)),
                ('g54_x', models.CharField(blank=True, db_index=True, max_length=5, null=True)),
                ('g54_y', models.CharField(blank=True, db_index=True, max_length=5, null=True)),
                ('g54_z', models.CharField(blank=True, db_index=True, max_length=5, null=True)),
                ('feed_start', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('feed_end', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('rpm_start', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('rpm_end', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('tool_lenght', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('coolant', models.BooleanField(blank=True, default=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('owner', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
            ],
        ),
    ]
