# Generated by Django 4.2.23 on 2025-08-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(blank=True, db_index=True, max_length=15, null=True)),
                ('code', models.TextField(blank=True, db_index=True, max_length=3000, null=True)),
            ],
        ),
    ]
